version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/ClassWorkRepository/Sprint_3/project
    docker:
      - image: cimg/node:lts
    steps: 
      - checkout:
          path: ~/ClassWorkRepository/Sprint_3/project
      - run: npm install --save-exact
      - run: npm test