version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/Sprint_3
    docker:
      - image: cimg/node:lts
    steps: 
      - checkout
      - run: npm install --save-exact
      - run: npm run start