version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    working_directory: ~/Sprint_3/project
    steps:
      - checkout
      - run:
          name: Remove node_modules and package-lock.json
          command: |
            rm -rf ~/Sprint_3/project/node_modules
            rm ~/Sprint_3/project/package-lock.json
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Check installed packages
          command: npm list --depth=0
      - run:
          name: Run tests
          command: npm test
