version: 2.1

orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/Sprint_3/project#
    docker:
      - image: cimg/node:lts
    steps: 
      - checkout:
        path: ~/Sprint_3
      - run: npm install

      
#   hello-job:
#     docker:
#       - image: cimg/node:17.2.0               # the primary container, where your job's commands are run
#     steps:
#       - checkout                              # check out the code in the project directory
#       - run: echo "hello world"               # print 'hello world'

# workflows:
#   my-workflow:                                # Name of the workflow. You can additional workflows below.
#     jobs:                                     # The jobs to run as part of this workflow
#       - hello-job                             # Example 'hello world' job.