version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/Sprint_3/project
    docker:
      - image: cimg/node:lts
    steps: 
      - checkout:
          path: ~/Sprint_3
      - run: npm install
      - run:
          name: Install Dependencies
          command: npm install --save-exact
      - run:
          name: Run Tests
          command: npm test