version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6-buster
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd ~/Sprint_3/project
            npm ci
      - run:
          name: Build and test
          command: |
            cd ~/Sprint_3/project
            npm run build
            npm test
